### ISSUE TITLE
Strange syntax on  searchareacontrol.selectedNodesChanged

### ISSUE THREAD

**Issue by jonathands** [kapantzak/SearchAreaControl#32]
$(document).on("searchareacontrol.selectedNodesChanged",function(elements,selectedNodes) {
		$(selectedNodes.selectedNodes.selectedNodes).each(function(i, node){	
			var inputHidden = $("<input>").attr("name","clientes[]").attr("type","hidden").attr("value",node.attributes["data-id"]);
			$('form').append(inputHidden);							
		});						
	});

I'm using the plugin within a form I'm developing and this $(selectedNodes.selectedNodes.selectedNodes) is bothering me greatly, Since it's a recent change on the plugin I'm not sure if this is an issue or just my implementation.

**Comment by kapantzak** [comment]
Hello jonathands,
The syntax is correct but I admit it'quite confusing. I will change the event in order to return an object with 3 properties: `element`,` selectedAll` and `selectedNodes`, so it can be used like this:

`$(document).on("searchareacontrol.selectedNodesChanged",function(elements,data) {
	$(data.selectedNodes).each(function(i, node){	
		var inputHidden = $("<input>").attr("name","clientes[]").attr("type","hidden").attr("value",node.attributes["data-id"]);
		$('form').append(inputHidden);							
	});						
});`

**Comment by kapantzak** [comment]
Event's returned object changed in version 1.5.0
